# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animations.root] run return 0
execute on passengers if entity @s[tag=aj.animations.data] unless data entity @s {data:{rigHash: '4e4a372f58b9b5eae66fed06923e778a185f5b4d64e9f8c4deb3e1a23b075b3d'}} on vehicle run function animated_java:animations/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1