# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animations.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animations', 'function_path': 'animated_java:animations/animations/swing_darksoul/stop'}
tag @s remove aj.animations.animation.swing_darksoul.playing
scoreboard players set @s aj.swing_darksoul.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:animations/animations/swing_darksoul/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only